apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  values:
    fullnameOverride: cert-manager
    crds:
      enabled: true
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::123848992453:role/raininfra-dev-cert-manager-role
    securityContext:
      fsGroup: 1001
