apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-rancher-token-reader
  namespace: cattle-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rancher-prometheus-token"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rancher-token-reader
  namespace: cattle-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-rancher-token-reader
subjects:
  - kind: ServiceAccount
    name: kube-prometheus-stack-operator
    namespace: monitoring
  - kind: ServiceAccount
    name: kube-prometheus-stack-prometheus
    namespace: monitoring
