apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    release: monitoring-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cattle-system
  selector:
    matchLabels:
      app: cattle-system-rancher
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 20s
      scheme: http
      honorLabels: true
