apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    release: monitoring-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cattle-system
  selector:
    matchLabels:
      app: cattle-system-rancher
  endpoints:
    - port: https-internal
      path: /metrics
      interval: 30s
      scrapeTimeout: 20s
      scheme: https
      honorLabels: true
      authorization:
        type: Bearer
        credentials:
          name: rancher-prometheus-token
          key: token
      tlsConfig:
        insecureSkipVerify: true
