apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  values:
    controller:
      ingressClass: nginx
      service:
        # TODO: Switch back to LoadBalancer once AWS enables ELB for this account
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      extraArgs:
        default-ssl-certificate: "ingress-nginx/bolunas-com-tls"
